# .goreleaser.yaml
version: 2

builds:
  -
    id: darwin
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

  -
    id: others
    env:
      - CGO_ENABLED=0
    targets:
      - aix_ppc64
      - android_arm64
      - dragonfly_amd64
      - freebsd_386
      - freebsd_amd64
      - freebsd_arm_5
      - freebsd_arm_6
      - freebsd_arm_7
      - freebsd_arm64
      - illumos_amd64
      - linux_386
      - linux_amd64
      - linux_arm_5
      - linux_arm_6
      - linux_arm_7
      - linux_arm64
      - linux_loong64
      - linux_mips
      - linux_mips_softfloat
      - linux_mipsle
      - linux_mipsle_softfloat
      - linux_mips64
      - linux_mips64_softfloat
      - linux_mips64le
      - linux_mips64le_softfloat
      - linux_ppc64
      - linux_ppc64le
      - linux_riscv64
      - linux_s390x
      - netbsd_386
      - netbsd_amd64
      - netbsd_arm_5
      - netbsd_arm_6
      - netbsd_arm_7
      - netbsd_arm64
      - openbsd_386
      - openbsd_amd64
      - openbsd_arm_5
      - openbsd_arm_6
      - openbsd_arm_7
      - openbsd_arm64
      - openbsd_ppc64
      - openbsd_riscv64
      - solaris_amd64
      - windows_386
      - windows_amd64
      - windows_arm64

changelog:
  disable: false
  use: github
  format: "{{.SHA}}: {{.Message}} (@{{.AuthorUsername}})"
  sort: asc
  abbrev: -1
release:
  footer: ""
